server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/demo-db
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/demo-db
    user: postgres
    password: postgres


logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE
