/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import com.google.common.math.IntMath;

@SuppressWarnings("java:S106")
public class HelloOtus {
    public static void main(String... args) {
        System.out.println(IntMath.binomial(6, 3));
    }
}
